### ISSUE TITLE
Suggestion: drop the 'null' line in type affinity example

### ISSUE THREAD

**Issue by Wolf-SO** [ReneNyffenegger/about-sqlite#1]
Foremost, thanks for providing [SQLite: type affinity of columns](https://renenyffenegger.ch/notes/development/databases/SQLite/tables/columns/type-affinity "SQLite: type affinity of columns") which is very helpful to understand the relation between declared types and actual types in columns.

The issue is that I found the last addition in `V` (`union all select  'null' v`) distracting and not informative. Wouldn't it be better to leave it out?

BTW: Sorry for opening the *Issues* section with this, I would have used [*Discussion*](https://docs.github.com/discussions/quickstart) if you had enabled it for this repository (which would also provide the appropriate space for a further exploration of this topic).

**Comment by ReneNyffenegger** [comment]
Thanks for the suggestion. I am not sure what crossed my mind when I've written that statement. It's changed now.

btw, I also learned about "Github Discussion" today... Very helpful - I might one day enable it one some of my repos.
